#!/bin/sh

# sets keyboard and mouse options
setxkbmap us
setxkbmap -option "terminate:ctrl_alt_bksp"
setxkbmap -option "caps:escape"
xmousepasteblock &

# starting the keyboard shortcuts deamon
sxhkd &

# some guy on the enternet said to paste it here
systemctl --user import-environment DISPLAY

# load color scheme and wallpaper
# wal -i ~/.config/wallpapers/. -q
wal -R -q
xrdb -merge ~/.Xresources &

#loading transparent background deamon
picom &

# load notifycation deamon
dunst &

# start screensaver deamon
xscreensaver --no-splash &

# mute the mic and the speaker
pamixer --source alsa_input.pci-0000_00_1f.3.analog-stereo -m &
pamixer -m &

# load WM and status background
slstatus &
exec dwm
